services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.17.15'
    ports:
      - '5601:5601'
    depends_on:
      - 'elasticsearch'